<?php

namespace App\Http\Controllers;

use App\Services\ProductService;
use Illuminate\Http\Response;

class ProductDataFileController extends Controller
{
    /**
     * Serve the products.js file containing the product data.
     *
     * @return Response
     */
    public function serveProductsJs(ProductService $product_service)
    {
        $product_data = $product_service->getAllProducts();

        $timestamp = now()->toDateTimeString();

        $js_data = <<<JS
            // Auto Generated by Http/Controllers/ProductDataFileController.php at {$timestamp}
            var list_products  = {$product_data->toJson(JSON_PRETTY_PRINT)};
        JS;

        // Return the response with the correct JavaScript content type
        return response($js_data)
            ->header('Content-Type', 'application/javascript');
    }
}
